[project]
name = "sccourts-probate-monthly-caseloads"
version = "0.1.0"
description = "An ETL pipeline for the South Carolina Supreme Court's Estate Workload Report at https://www.sccourts.org/about/statistics-reports/archived-reports-statistics/annual-reports/"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=3.0.5",
    "pdfplumber>=0.11.10",
    "pyarrow>=25.0.1",
    "requests>=2.34.2",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
